version: '3.1'

services:
  otusdb:
    image: mysql:8.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command:
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./conf.d:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3306:3306"

volumes:
  data: